import '@/styles/globals.css'
import { roboto } from '@/styles/fonts'

import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
import ToastProvider from '@/providers/toast-provider'

export const metadata = {
  title: 'Cirbit',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ToastProvider />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
