import './globals.css'
import { Poppins } from 'next/font/google'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'

const poppins = Poppins({
  weight: "400",
  subsets: ['latin'],
  style: "normal"
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
